services:

  todoservices:
    build: .
    container_name: todoservices
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    ports:
      - "8080:8080"
    environment:
      APP_ADDRESS: ":8080"
      PREFIX: "api/v1"
      NAME: "Yet Another Over Engineer Todo"
      ENABLEPRINTROUTES: true
      SERVERHEADER: "Todo Engineer"
      ALLOWORIGINS: "*"
      ALLOWMETHODS: "GET,POST,PUT,DELETE,OPTIONS"
      ALLOWHEADERS: "Content-Type, Authorization"
      ALLOWCREDENTIALS: false
      JSONPLACEHOLDER: "https://jsonplaceholder.typicode.com/todos"
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    image: postgres:15.2-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "tododb"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  #pgadmin:
  #  image: dpage/pgadmin4:6.20
  #  container_name: pgadmin
  #  ports:
  #    - "5050:80"
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #    PGADMIN_DEFAULT_PASSWORD: "secret"
  #  depends_on:
  #    database:
  #      condition: service_healthy
  #  restart: unless-stopped
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - "8081:8080"
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped


volumes:
  db_data:
  go-mod-cache:
