basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: alexandrodisla@hotmail.com
    name: AD0791
  description: API documentation for Todo service with persistence
  termsOfService: Developpement
  title: Todo API Documentation
  version: "1.1"
paths: {}
swagger: "2.0"
