basePath: /api/v1
definitions:
  filemodel.Todo:
    properties:
      completed:
        type: boolean
      id:
        type: integer
      title:
        minLength: 3
        type: string
    required:
    - title
    type: object
  schema.MessageResponse:
    properties:
      id:
        type: integer
      message:
        type: string
    type: object
  schema.MessageSQLResponse:
    properties:
      deleted_at:
        example: "2023-01-01"
        type: string
      id:
        type: integer
      message:
        type: string
    type: object
  schema.TodoRequest:
    properties:
      completed:
        description: example:"false"
        example: false
        type: boolean
      title:
        description: example:"Sample Todo"
        example: Sample Todo
        minLength: 3
        type: string
    required:
    - title
    type: object
  schema.TodoResponse:
    properties:
      completed:
        type: boolean
      id:
        type: integer
      title:
        minLength: 3
        type: string
    required:
    - title
    type: object
  schema.TodoSQLResponse:
    properties:
      completed:
        example: false
        type: boolean
      created_at:
        description: Formatted date
        example: "2023-01-01"
        type: string
      id:
        example: 1
        type: integer
      title:
        example: Sample Todo
        type: string
      updated_at:
        description: Formatted date
        example: "2023-01-01"
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: alexandrodisla@hotmail.com
    name: AD0791
  description: API documentation for Todo service with persistence
  termsOfService: Developpement
  title: Todo API Documentation
  version: "1.1"
paths:
  /file/todos:
    get:
      consumes:
      - application/json
      description: Retrieve all todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/filemodel.Todo'
            type: array
      summary: Get all todos
      tags:
      - file
    post:
      consumes:
      - application/json
      description: Add a new todo to the list
      parameters:
      - description: Todo to create
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/schema.TodoRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/filemodel.Todo'
        "400":
          description: Validation error
          schema:
            type: string
      summary: Create a new todo
      tags:
      - file
  /file/todos/{id}:
    delete:
      consumes:
      - application/json
      description: Remove a todo from the json list
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/schema.MessageResponse'
        "404":
          description: Todo not found
          schema:
            type: string
      summary: Delete a todo
      tags:
      - file
    get:
      consumes:
      - application/json
      description: Retrieve a single todo by its ID
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/filemodel.Todo'
        "404":
          description: Todo not found
          schema:
            type: string
      summary: Get todo by ID
      tags:
      - file
    put:
      consumes:
      - application/json
      description: Modify an existing todo
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated todo data
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/schema.TodoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.TodoResponse'
        "400":
          description: Validation error
          schema:
            type: string
        "404":
          description: Todo not found
          schema:
            type: string
      summary: Update a todo
      tags:
      - file
  /service/todos:
    get:
      consumes:
      - application/json
      description: Retrieve all todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schema.TodoResponse'
            type: array
      summary: Get all todos
      tags:
      - service
    post:
      consumes:
      - application/json
      description: Add a new todo to the list
      parameters:
      - description: Todo to create
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/schema.TodoRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schema.TodoResponse'
        "400":
          description: Validation error
          schema:
            type: string
      summary: Create a new todo
      tags:
      - service
  /service/todos/{id}:
    delete:
      consumes:
      - application/json
      description: Remove a todo from the list
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/schema.MessageResponse'
        "404":
          description: Todo not found
          schema:
            type: string
      summary: Delete a todo
      tags:
      - service
    get:
      consumes:
      - application/json
      description: Retrieve a single todo by its ID
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.TodoResponse'
        "404":
          description: Todo not found
          schema:
            type: string
      summary: Get todo by ID
      tags:
      - service
    put:
      consumes:
      - application/json
      description: Modify an existing todo
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated todo data
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/schema.TodoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.TodoResponse'
        "400":
          description: Validation error
          schema:
            type: string
        "404":
          description: Todo not found
          schema:
            type: string
      summary: Update a todo
      tags:
      - service
  /sql/todos:
    get:
      consumes:
      - application/json
      description: Retrieve all todos from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schema.TodoSQLResponse'
            type: array
        "500":
          description: Database error
          schema:
            type: string
      summary: Get all todos
      tags:
      - sql
    post:
      consumes:
      - application/json
      description: Create a new todo
      parameters:
      - description: Todo request body
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/schema.TodoRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schema.TodoSQLResponse'
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Database error
          schema:
            type: string
      summary: Create todo
      tags:
      - sql
  /sql/todos/{id}:
    delete:
      consumes:
      - application/json
      description: Soft delete a todo by ID
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/schema.MessageSQLResponse'
        "400":
          description: Invalid ID
          schema:
            type: string
        "404":
          description: Todo not found
          schema:
            type: string
        "500":
          description: Database error
          schema:
            type: string
      summary: Delete todo
      tags:
      - sql
    get:
      consumes:
      - application/json
      description: Retrieve a single todo by its ID
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.TodoSQLResponse'
        "400":
          description: Invalid ID
          schema:
            type: string
        "404":
          description: Todo not found
          schema:
            type: string
      summary: Get todo by ID
      tags:
      - sql
    put:
      consumes:
      - application/json
      description: Update an existing todo
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated todo data
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/schema.TodoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.TodoSQLResponse'
        "400":
          description: Invalid ID
          schema:
            type: string
        "404":
          description: Todo not found
          schema:
            type: string
        "500":
          description: Database error
          schema:
            type: string
      summary: Update todo
      tags:
      - sql
schemes:
- http
swagger: "2.0"
tags:
- description: File-based todo operations
  name: file
- description: Service-based todo operations
  name: service
- description: SQL-based todo operations
  name: sql
